# Generated by Django 5.0.7 on 2024-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
